extern void __VERIFIER_error() __attribute__ ((__noreturn__));

/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

void __blast_assert(void) 
{ 
  ERROR: __VERIFIER_error();
}
int main(void) 
{ 
	int i ;
	i = 0;
	while (1) {
		if (i >= 5) {
			break;
		}
		i = i + 1;
		__blast_assert();
	}
	return (0);
}
